### ISSUE TITLE
Failure=blank only when using randomize map flag

### ISSUE THREAD

**Issue by Crono1999** [Gilmok/UWNHRando#7]
[diffreport-SUCCESS.txt](https://github.com/Gilmok/UWNHRando/files/8403018/diffreport-SUCCESS.txt)
[makeLog-FAILURE.txt](https://github.com/Gilmok/UWNHRando/files/8403019/makeLog-FAILURE.txt)
[makeLog-SUCCESS.txt](https://github.com/Gilmok/UWNHRando/files/8403020/makeLog-SUCCESS.txt)

I am able to use the randomizer to generate random ROMs using any of the selected flags except for the randomize map flag. Every time I use the randomize map flag, whether by itself or in any combination of other flags, I receive the below error message every time.

_nullThis seed failed to successfully generate a ROM.
Failure=
See makelog for details._

I attached a makeLog file that was a failure, and a subsequent makeLog and diffreport from when I did not select randomize map and it was successful (same seed/ROM tested for all attached files).

If I select any combo of options outside of the randomize map option, the random ROM is generated successfully and those criteria work in game, confirmed by starting games as Ernst and Otto and being assigned different starting ships as well as finding different trade goods in their starting ports.

I have tested having the ROM in my randomizer folder, in a folder inside my randomizer folder, in my C:Documents folder as well as a folder on an entirely separate drive and nothing seems to change the results. I'll also point out that using the randomize map option paired with the map preview flag will fail, but it does generate a map preview that I would assume is the map that I would receive if the file had successfully generated.  The map preview will differ every time based on the selected seed and if any of the continent/island/ice cap sliders are adjusted. 

Last thing I'll add just to cover as many bases as possible is my computer shows I have the following version of Java installed. **Java 8 Update 321 (64-bit)**

**Comment by Gilmok** [comment]
I looked at the failure case you sent me (seed and flags) and I was able to successfully generate that rom.

If you look at the randomizer's Theme tab, you should see a list of Kingdoms, Areas, Ports, Supply Ports, Discoveries, and Commodities.  Make sure everything in there is human readable (no garbage).

Also, what size is your ROM?  The randomizer should be compatible with both headered and headerless roms (it is a 512 byte header if you have one), but I personally used a headered rom.

**Comment by Crono1999** [comment]
ROM Size: 2.00 MB (2,097,152 bytes) with the following checksum info: 

CRC32: 3C3C63E6
CRC64: D9B5D253769F93BE
SHA256: 64BC4707F422661A66618088887E2363A5F896EA683C58984FFFD96DD21AB5F0
SHA1: E63BCBED001C63011DF0AC043BC56D0FE323482F

I did check the randomizer's Theme tab and when I select Edit All under any given tab, the info I see populated is what I would expect to see in game for those fields (whether they are port names, discoveries, trade goods etc).

**Comment by Gilmok** [comment]
I found the issue and have uploaded the fix.  Let me know if it works for you so I can close the issue.

**Comment by Crono1999** [comment]
You're a genius, you can close it up this is working just fine now thanks again.

**Comment by Gilmok** [comment]
If you knew what caused the issue you'd put a dunce cap on my head.  I'm hoping to remove my many dunce caps someday.

Glad to see it working better.
